apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master 
  name: 99-master-ntnx-iscsid-conf
  spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - path: /etc/iscsi/iscsid.conf
        mode: 0600
        overwrite: true
        contents:
          inline: |
            node.session.timeo.replacement_timeout = 120
            node.conn[0].timeo.noop_out_interval = 5
            node.conn[0].timeo.noop_out_timeout = 10
            node.session.cmds_max = 2048
            node.session.queue_depth = 1024
            node.session.iscsi.ImmediateData = Yes
            node.session.iscsi.FirstBurstLength = 1048576
            node.session.iscsi.MaxBurstLength = 16776192
            node.conn[0].iscsi.MaxRecvDataSegmentLength = 1048576
            discovery.sendtargets.iscsi.MaxRecvDataSegmentLength = 1048576
            iscsid.startup = /bin/systemctl start iscsid.socket iscsiuio.socket
            node.startup = automatic
            node.leading_login = No
            node.conn[0].timeo.login_timeout = 15
            node.conn[0].timeo.logout_timeout = 15
            node.session.err_timeo.abort_timeout = 15
            node.session.err_timeo.lu_reset_timeout = 30
            node.session.err_timeo.tgt_reset_timeout = 30
            node.session.initial_login_retry_max = 8
            node.session.xmit_thread_priority = -20
            node.session.iscsi.InitialR2T = No
            node.conn[0].iscsi.MaxXmitDataSegmentLength = 0
            discovery.sendtargets.iscsi.MaxRecvDataSegmentLength = 32768
            node.conn[0].iscsi.HeaderDigest = None
            node.session.nr_sessions = 1
            node.session.reopen_max = 0
            node.session.iscsi.FastAbort = Yes
            node.session.scan = auto