apiVersion: v1
kind: Secret
metadata:
  name: ntnx-secret
  namespace: openshift-cluster-csi-drivers
stringData:
  # prism-ip:prism-port:username:password.
  key: 192.168.80.17:9440:nutanix:Nutanix/4u